defaults:
  - datamodule

dataset:
  _target_: src.datamodules.datasets.opt_mini.OptMini
  len_data: 5000
  sigma: 50


# ig this should also be length of weights (will be set later)
ndim: 41
# This should be length of weights (will be set later)
shape: 41
