defaults:
  - datamodule

dataset:
  _target_: src.datamodules.datasets.opt_mini.OptMini
  len_data: 5000
  sigma: 50


# ig this should also be no. of task model params (will be set later)
ndim: 10 # 41
# This should be no. of task model params (will be set later)
shape: 10 # 41
